### ISSUE TITLE
Feature Request: support iPad Pro screenshot

### ISSUE THREAD

**Issue by labolado** [colinhumber/itunes_transporter_generator#31]
support iPad Pro screenshot

**Comment by maxbritto** [comment]
As written in this project readme : you should check out project that are actively maintained like deliver (https://github.com/KrauseFx/deliver) or fastlane (which is the parent project of deliver)

**Comment by colinhumber** [comment]
Ya, as @maxbritto said, this project has been sunsetted. The excellent Deliver and the other tools from Felix are the preferred way to go. Also, since they have been acquired by Twitter, they will be maintained for the foreseeable future. Thanks for using my tool, though!
